AppGiros/Controllers/CiudadController.cs
using AppGiros.Manejadores;
using AppGiros.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data.SqlClient;
using System.Drawing.Printing;

namespace AppGiros.Controllers
{
    public class CiudadController : Controller
    {
        public IConfiguration Configuration { get; set; }
        public ManejadorCiudad _manejadorCiudad { get; set; }

        public CiudadController(IConfiguration configuration, ManejadorCiudad manejadorCiudad) 
        {
            Configuration = configuration;
            _manejadorCiudad = manejadorCiudad;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult ObtenerCiudades(int page = 1, int pageSize = 15)
        {
            try
            {
                // restriccion de resultados para paginacion
                var listaCiudades = _manejadorCiudad.ObtenerCiudades()
                .Skip((page - 1) * pageSize)
                .Take(pageSize)
                .ToList();

                var totalCiudades = _manejadorCiudad.ObtenerCiudades().Count();

                return Ok(new { ciudades = listaCiudades, totalCiudades });
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        [HttpDelete]
        public IActionResult EliminarCiudad(int idCiudad)
        {
            try
            {
                bool eliminada = _manejadorCiudad.EliminarCiudad(idCiudad);
                return Ok(eliminada);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        [HttpGet]
        public JsonResult ObtenerCiudadesPais(int idPais)
        {
            var ciudadesPais = _manejadorCiudad.ObtenerCiudadesPais(idPais);
            return Json(ciudadesPais);
        }

        [HttpPost]
        public IActionResult GuardarCiudad(CiudadesModels ciudad)
        {
            bool respuesta;
            try
            {
                respuesta = _manejadorCiudad.GuardarCiudad(ciudad); 
                return Ok(respuesta);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

    }
}

AppGiros/Controllers/GirosController.cs
using AppGiros.Manejadores;
using AppGiros.Models;
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;

namespace AppGiros.Controllers
{
    public class GirosController : Controller
    {

        public IConfiguration Configuration { get; set; }
        public ManejadorGiros _manejadorGiros { get; set; }

        public GirosController(IConfiguration configuration, ManejadorGiros manejadorGiros)
        {
            Configuration = configuration;
            _manejadorGiros = manejadorGiros;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public JsonResult GetGiros(int idCiudad)
        {
            List<ConvertirJson> list = new List<ConvertirJson>();

            using (SqlConnection conexion = new SqlConnection(Configuration["ConnectionStrings:ConnectionStringSQLServer"]))
            {
                string query = "SELECT TOP 5 GIR_GIRO_ID, GIR_RECIBO FROM GIROS WHERE GIR_CIUDAD_ID = @idCiudad";
                conexion.Open();

                using (SqlCommand command = new SqlCommand(query, conexion))
                {
                    // Agregar el parámetro
                    command.Parameters.AddWithValue("@idCiudad", idCiudad); 

                    using SqlDataReader reader = command.ExecuteReader();
                    while (reader.Read())
                    {
                        // Leer los datos de cada registro y agregarlos a la lista de ciudades
                        ConvertirJson item = new ConvertirJson
                        {
                            Value = reader.GetInt32(0),
                            Text = reader.GetString(1),
                        };

                        list.Add(item);
                    }
                }
            }
            return Json(list); 
        }

        [HttpGet]
        public JsonResult ObtenerGirosCiudad(int idCiudad)
        {
            var giros = _manejadorGiros.ObtenerGirosCiudad(idCiudad);
            return Json(giros);
        }

        [HttpPost]
        public IActionResult CrearGiro([FromBody] GirosModels giro)
        {
            if (giro == null || string.IsNullOrEmpty(giro.Recibo))
            {
                return BadRequest("Datos inválidos para crear el giro.");
            }

            try
            {
                _manejadorGiros.CrearGiro(giro);
                return Ok("Giro creado exitosamente.");
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"Error al crear el giro: {ex.Message}");
            }
        }

        [HttpPut]
        public IActionResult EditarGiro(GirosModels giro)
        {
            if (giro == null || giro.Id <= 0)
            {
                return BadRequest("Datos inválidos para editar el giro.");
            }

            try
            {
                _manejadorGiros.EditarGiro(giro);
                return Ok("Giro editado exitosamente.");
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"Error al editar el giro: {ex.Message}");
            }
        }

        [HttpDelete]
        public IActionResult EliminarGiro(int id)
        {
            if (id <= 0)
            {
                return BadRequest("ID inválido para eliminar el giro.");
            }

            try
            {
                _manejadorGiros.EliminarGiro(id);
                return Ok("Giro eliminado exitosamente.");
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"Error al eliminar el giro: {ex.Message}");
            }
        }

    }
}

AppGiros/Controllers/PaisesController.cs
using AppGiros.Manejadores;
using AppGiros.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Data.SqlClient;

namespace AppGiros.Controllers
{
    public class PaisesController : Controller
    {
        public IConfiguration Configuration { get; set; }
        public ManejadorPais _manejadorPais { get; set; }

        public PaisesController(IConfiguration configuration, ManejadorPais manejadorPais)
        {
            Configuration = configuration;
            _manejadorPais = manejadorPais;
        }

        public IActionResult Index()
        {
            List<SelectListItem> listaPaises = new List<SelectListItem>();

            using (SqlConnection conexion = new(Configuration["ConnectionStrings:ConnectionStringSQLServer"]))
            {
                string query = "SELECT * FROM PAISES";
                conexion.Open();

                using (SqlCommand command = new SqlCommand(query, conexion))
                {
                    using SqlDataReader reader = command.ExecuteReader();
                    while (reader.Read())
                    {

                        // Leer los datos de cada registro y agregarlos a la lista de ciudades
                        SelectListItem item = new SelectListItem
                        {
                            Value = reader.GetInt32(0).ToString(),
                            Text = reader.GetString(1),
                        };

                        listaPaises.Add(item);

                    }
                }

                conexion.Close();
            }
            return View(listaPaises);
        }

        public IActionResult GuardarPais()
        {
            return View();
        }

        [HttpPost]
        public IActionResult GuardarPais(PaisesModels pais)
         {
            using (SqlConnection conexion = new(Configuration["ConnectionStrings:ConnectionStringSQLServer"]))
            {
                using (SqlCommand cmd = new("sp_guardarPais", conexion))
                {
                    cmd.CommandType = System.Data.CommandType.StoredProcedure;
                    cmd.Parameters.Add("nombre", System.Data.SqlDbType.VarChar).Value = pais.Nombre;
                    conexion.Open();
                    cmd.ExecuteNonQuery();
                    conexion.Close();
                }
            }
            return Redirect("Index");
        }

        public IActionResult EditarPais()
        {
            return View();
        }

        [HttpPut]
        public IActionResult EditarPais(PaisesModels pais)
        {
            using (SqlConnection conexion = new(Configuration["ConnectionStrings:ConnectionStringSQLServer"]))
            {

                // Crear la consulta SQL para actualizar el registro
                string query = "UPDATE PAIS SET Nombre = @Nombre WHERE Id = @Id";
                conexion.Open();

                using (SqlCommand command = new SqlCommand(query, conexion))
                {
                    // Pasar los parámetros a la consulta SQL
                    command.Parameters.AddWithValue("@Nombre", pais.Nombre);

                    // Ejecutar la consulta SQL
                    command.ExecuteNonQuery();
                }
            }

            // Redirigir a una página de éxito o mostrar un mensaje de éxito
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult ObtenerPaises()
        {
            var paises = _manejadorPais.ObtenerPaises(); 
            return Json(paises);
        }
    }
}

AppGiros/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AppGiros</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AppGiros.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AppGiros</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li> 
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Paises" asp-action="Index">Paises</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ciudad" asp-action="Index">Ciudades</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Giros" asp-action="Index">Giros</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            Leonardo Tejero - Proyecto Giros
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>